const archetypes = {
    "MonoGeo": {description: "Arquetipo basado en personajes del elemento Geo. Estos personajes suelen tener sinergia entre ellos. Se juegan con tres o cuatro personajes geo y un personaje flex. Destacan dps como Ningguang, Noelle o Itto. El uso de Gorou no es siempre obligatorio, pero si suele estar bastante presente en este arquetipo.", elements: ["Geo", "Geo", "Geo", "Flex"], pros_cons: "Fáciles de jugar, no se ve bloqueado por ningún tipo de escudo elemental, aunque no suelen ser muy efectivos contra estos", example_teams: [], color: "", forced_characters: []},
    "MonoHydro": {description: "Arquetipo basado en el uso de personajes del elemento Hydro. Está compuesto de tres personajes Hydro mas un personaje Anemo, que se encarga de bajar la resistencia Hydro gracias a VV. También se puede usar a Zhongli para bajar esta resistencia y tener utilidad defensiva.", elements: ["Hydro", "Hydro", "Hydro", "Flex"], pro_cons:"Gracias a Furina este arquetipo ha mejorado muchísimo, y ya no depende de Xingqiu y Yelan, existiendo muchas alternativas. Destaca al romper escudos de fuego, y suelen tener un daño single-target muy potente. En algunas situaciones, añadir un personaje electro puede resultar en un mejor equipo.", example_teams: [], color: "", forced_characters: []},
    "MonoCryo": {description: "Arquetipo basado en el uso de personajes del elemento Cryo. Está compuesto de tres personajes Cryo mas un personaje Anemo, que se encarga de bajar la resistencia Hydro gracias a VV.", elements: [], pro_cons: "Es objetivamente inferior al arquetipo Freeze... a no ser que el enemigo no se pueda congelar. En estos casos, lo supera y se convierte en una muy buena alternativa, por ejemplo, contra jefes.", example_teams: [], color: "", forced_characters: ["Kaedehara Kazuha", "Shenhe"]},
    "MonoPyro": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: [""]},
    "MonoElectro": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "MonoAnemo": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Hypercarry": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Freeze": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "National": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Vaporize": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Overvape": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Taser": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Soup": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Melt": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Aggravate": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Spread": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Bloom": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Burgeon": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Oven": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Curry": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Sauté": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Fridge": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Salad": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Airfryer": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Hyperbloom": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Quickbloom": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "HyperFridge": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Overload": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
    "Bain-Marie": {description: "", elements: [], pros: "", cons: "", example_teams: [], color: "", forced_characters: []},
};
