const artifacts =
    [
        "Adventurer",
        "Archaic Petra",
        "Berserker",
        "Blizzard Strayer",
        "Bloodstained Chivalry",
        "Brave Heart",
        "Crimson Witch of Flames",
        "Deepwood Memories",
        "Defender's Will",
        "Desert Pavilion Chronicle",
        "Echoes of an Offering",
        "Emblem of Severed Fate",
        "Flower of Paradise Lost",
        "Gambler",
        "Gilded Dreams",
        "Gladiator's Finale",
        "Golden Troupe",
        "Heart of Depth",
        "Husk of Opulent Dreams",
        "Instructor",
        "Lavawalker",
        "Lucky Dog",
        "Maiden Beloved",
        "Marechaussee Hunter",
        "Martial Artist",
        "Noblesse Oblige",
        "Nymph's Dream",
        "Ocean-Hued Clam",
        "Pale Flame",
        "Prayers for Destiny",
        "Prayers for Illumination",
        "Prayers for Wisdom",
        "Prayers to Springtime",
        "Resolution of Sojourner",
        "Retracing Bolide",
        "Scholar",
        "Shimenawa's Reminiscence",
        "Tenacity of the Millelith",
        "The Exile",
        "Thundering Fury",
        "Thundersoother",
        "Tiny Miracle",
        "Traveling Doctor",
        "Vermillion Hereafter",
        "Viridescent Venerer",
        "Vourukasha's Glow",
        "Wanderer's Troupe"
    ]