const best_teams = {
    "Aether": [],
    "Albedo": [],
    "Alhaitham": [],
    "Aloy": [],
    "Amber": [],
    "Arataki Itto": [],
    "Baizhu": [],
    "Barbara": [],
    "Beidou": [],
    "Bennett": [],
    "Candace": [],
    "Chongyun": [],
    "Collei": [],
    "Cyno": [],
    "Dehya": [],
    "Diluc": [],
    "Diona": [],
    "Dori": [],
    "Eula": [],
    "Faruzan": [],
    "Fischl": [],
    "Freminet": [],
    "Ganyu": [],
    "Gorou": [],
    "Hu Tao": [],
    "Jean": [],
    "Kaedehara Kazuha": [],
    "Kaeya": [],
    "Kamisato Ayaka": [],
    "Kamisato Ayato": [],
    "Kaveh": [],
    "Keqing": [],
    "Kirara": [],
    "Klee": [],
    "Kujou Sara": [],
    "Kuki Shinobu": [],
    "Layla": [],
    "Lisa": [],
    "Lumine": [],
    "Lynette": [],
    "Lyney": [],
    "Mika": [],
    "Mona": [],
    "Nahida": [],
    "Nilou": [],
    "Ningguang": [],
    "Noelle": [],
    "Qiqi": [],
    "Raiden Shogun": [],
    "Razor": [],
    "Rosaria": [],
    "Sangonomiya Kokomi": [],
    "Sayu": [],
    "Shenhe": [],
    "Shikanoin Heizou": [],
    "Sucrose": [],
    "Tartaglia": [],
    "Thoma": [],
    "Tighnari": [],
    "Venti": [],
    "Wanderer": [],
    "Xiangling": [],
    "Xiao": [],
    "Xingqiu": [],
    "Xinyan": [],
    "Yae Miko": [],
    "Yanfei": [],
    "Yaoyao": [],
    "Yelan": [],
    "Yoimiya": [],
    "Yun Jin": [],
    "Zhongli": []
}