const characters_release_date = {
    "Aether": "1",
    "Albedo": "27",
    "Alhaitham": "62",
    "Aloy": "38",
    "Amber": "15",
    "Arataki Itto": "43",
    "Baizhu": "66",
    "Barbara": "19",
    "Beidou": "12",
    "Bennett": "8",
    "Candace": "55",
    "Chongyun": "5",
    "Collei": "53",
    "Cyno": "56",
    "Dehya": "64",
    "Diluc": "17",
    "Diona": "22",
    "Dori": "54",
    "Eula": "33",
    "Faruzan": "60",
    "Fischl": "9",
    "Freminet": "71",
    "Ganyu": "28",
    "Gorou": "44",
    "Hu Tao": "30",
    "Jean": "21",
    "Kaedehara Kazuha": "34",
    "Kaeya": "18",
    "Kamisato Ayaka": "35",
    "Kamisato Ayato": "48",
    "Kaveh": "67",
    "Keqing": "3",
    "Kirara": "68",
    "Klee": "23",
    "Kujou Sara": "39",
    "Kuki Shinobu": "50",
    "Layla": "59",
    "Lisa": "20",
    "Lumine": "1",
    "Lynette": "70",
    "Lyney": "69",
    "Mika": "65",
    "Mona": "4",
    "Nahida": "58",
    "Nilou": "57",
    "Ningguang": "10",
    "Noelle": "7",
    "Qiqi": "6",
    "Raiden Shogun": "40",
    "Razor": "16",
    "Rosaria": "31",
    "Sangonomiya Kokomi": "41",
    "Sayu": "36",
    "Shenhe": "46",
    "Shikanoin Heizou": "51",
    "Sucrose": "2",
    "Tartaglia": "24",
    "Thoma": "42",
    "Tighnari": "52",
    "Venti": "14",
    "Wanderer": "61",
    "Xiangling": "13",
    "Xiao": "29",
    "Xingqiu": "11",
    "Xinyan": "25",
    "Yae Miko": "47",
    "Yanfei": "32",
    "Yaoyao": "63",
    "Yelan": "49",
    "Yoimiya": "37",
    "Yun Jin": "45",
    "Zhongli": "26"
}
