const characters_emojis = {
    "Aether": "Icon_Emoji_Paimon's_Paintings_01_Aether_2.webp",
    "Lumine": "Icon_Emoji_Paimon's_Paintings_01_Lumine_2.webp",
    "Sucrose": "Icon_Emoji_Paimon's_Paintings_20_Sucrose_1.webp",
    "Keqing": "Icon_Emoji_Paimon's_Paintings_02_Keqing_1.webp",
    "Mona": "Icon_Emoji_Paimon's_Paintings_02_Mona_2.webp",
    "Chongyun": "Icon_Emoji_Paimon's_Paintings_27_Chongyun_1.webp",
    "Qiqi": "Icon_Emoji_Paimon's_Paintings_02_Qiqi_1.webp",
    "Noelle": "Icon_Emoji_Paimon's_Paintings_27_Noelle_1.webp",
    "Bennett": "Icon_Emoji_Paimon's_Paintings_20_Bennett_1.webp",
    "Fischl": "Icon_Emoji_Paimon's_Paintings_04_Fischl_1.webp",
    "Ningguang": "Icon_Emoji_Paimon's_Paintings_21_Ningguang_1.webp",
    "Xingqiu": "Icon_Emoji_Paimon's_Paintings_14_Xingqiu_1.webp",
    "Beidou": "Icon_Emoji_Paimon's_Paintings_08_Beidou_1.webp",
    "Xiangling": "Icon_Emoji_Paimon's_Paintings_09_Xiangling_1.webp",
    "Venti": "Icon_Emoji_Paimon's_Paintings_22_Venti_1.webp",
    "Amber": "Icon_Emoji_Paimon's_Paintings_01_Amber_1.webp",
    "Razor": "Icon_Emoji_Paimon's_Paintings_18_Razor_2.webp",
    "Diluc": "Icon_Emoji_Paimon's_Paintings_13_Diluc_1.webp",
    "Kaeya": "Icon_Emoji_Paimon's_Paintings_25_Kaeya_2.webp",
    "Barbara": "Icon_Emoji_Paimon's_Paintings_07_Barbara_3.webp",
    "Lisa": "Icon_Emoji_Paimon's_Paintings_13_Lisa_1.webp",
    "Jean": "Icon_Emoji_Paimon's_Paintings_07_Jean_1.webp",
    "Diona": "Icon_Emoji_Paimon's_Paintings_20_Diona_1.webp",
    "Klee": "Icon_Emoji_Paimon's_Paintings_25_Klee_3.webp",
    "Tartaglia": "Icon_Emoji_Paimon's_Paintings_10_Tartaglia_1.webp",
    "Xinyan": "Icon_Emoji_Paimon's_Paintings_03_Xinyan_1.webp",
    "Zhongli": "Icon_Emoji_Paimon's_Paintings_12_Zhongli_1.webp",
    "Albedo": "Icon_Emoji_Paimon's_Paintings_11_Albedo_1.webp",
    "Ganyu": "Icon_Emoji_Paimon's_Paintings_04_Ganyu_5.webp",
    "Xiao": "Icon_Emoji_Paimon's_Paintings_15_Xiao_1.webp",
    "Hu Tao": "Icon_Emoji_Paimon's_Paintings_05_Hu_Tao_1.webp",
    "Rosaria": "Icon_Emoji_Paimon's_Paintings_06_Rosaria_1.webp",
    "Yanfei": "Icon_Emoji_Paimon's_Paintings_06_Yanfei_4.webp",
    "Eula": "Icon_Emoji_Paimon's_Paintings_06_Eula_2.webp",
    "Kaedehara Kazuha": "Icon_Emoji_Paimon's_Paintings_16_Kaedehara_Kazuha_2.webp",
    "Kamisato Ayaka": "Icon_Emoji_Paimon's_Paintings_14_Kamisato_Ayaka_1.webp",
    "Sayu": "Icon_Emoji_Paimon's_Paintings_08_Sayu_3.webp",
    "Yoimiya": "Icon_Emoji_Paimon's_Paintings_16_Yoimiya_1.webp",
    "Aloy": "",
    "Kujou Sara": "Icon_Emoji_Paimon's_Paintings_09_Kujou_Sara_2.webp",
    "Raiden Shogun": "Icon_Emoji_Paimon's_Paintings_13_Raiden_Shogun_2.webp",
    "Sangonomiya Kokomi": "Icon_Emoji_Paimon's_Paintings_13_Sangonomiya_Kokomi_1.webp",
    "Thoma": "Icon_Emoji_Paimon's_Paintings_10_Thoma_3.webp",
    "Arataki Itto": "Icon_Emoji_Paimon's_Paintings_11_Arataki_Itto_1.webp",
    "Gorou": "Icon_Emoji_Paimon's_Paintings_11_Gorou_4.webp",
    "Yun Jin": "Icon_Emoji_Paimon's_Paintings_12_Yun_Jin_2.webp",
    "Shenhe": "Icon_Emoji_Paimon's_Paintings_12_Shenhe_3.webp",
    "Yae Miko": "Icon_Emoji_Paimon's_Paintings_24_Yae_Miko_1.webp",
    "Kamisato Ayato": "Icon_Emoji_Paimon's_Paintings_14_Kamisato_Ayato_2.webp",
    "Yelan": "Icon_Emoji_Paimon's_Paintings_21_Yelan_1.webp",
    "Kuki Shinobu": "Icon_Emoji_Paimon's_Paintings_15_Kuki_Shinobu_2.webp",
    "Shikanoin Heizou": "Icon_Emoji_Paimon's_Paintings_16_Shikanoin_Heizou_3.webp",
    "Tighnari": "Icon_Emoji_Paimon's_Paintings_17_Tighnari_4.webp",
    "Collei": "Icon_Emoji_Paimon's_Paintings_17_Collei_2.webp",
    "Dori": "Icon_Emoji_Paimon's_Paintings_17_Dori_2.webp",
    "Candace": "Icon_Emoji_Paimon's_Paintings_18_Candace_1.webp",
    "Cyno": "Icon_Emoji_Paimon's_Paintings_18_Cyno_3.webp",
    "Nilou": "Icon_Emoji_Paimon's_Paintings_18_Nilou_4.webp",
    "Nahida": "Icon_Emoji_Paimon's_Paintings_23_Nahida_2.webp",
    "Layla": "Icon_Emoji_Paimon's_Paintings_23_Layla_1.webp",
    "Faruzan": "Icon_Emoji_Paimon's_Paintings_23_Faruzan_1.webp",
    "Wanderer": "Icon_Emoji_Paimon's_Paintings_20_Wanderer_3.webp",
    "Alhaitham": "Icon_Emoji_Paimon's_Paintings_21_Alhaitham_2.webp",
    "Yaoyao": "Icon_Emoji_Paimon's_Paintings_21_Yaoyao_2.webp",
    "Dehya": "Icon_Emoji_Paimon's_Paintings_22_Dehya_3.webp",
    "Mika": "Icon_Emoji_Paimon's_Paintings_22_Mika_1.webp",
    "Baizhu": "Icon_Emoji_Paimon's_Paintings_23_Baizhu_1.webp",
    "Kaveh": "Icon_Emoji_Paimon's_Paintings_23_Kaveh_5.webp",
    "Kirara": "Icon_Emoji_Paimon's_Paintings_24_Kirara_1.webp",
    "Lyney": "Icon_Emoji_Paimon's_Paintings_26_Lyney_1.webp",
    "Lynette": "Icon_Emoji_Paimon's_Paintings_26_Lynette_4.webp",
    "Freminet": "Icon_Emoji_Paimon's_Paintings_28_Freminet_1.webp",
    "Neuvillette": "Icon_Emoji_Paimon's_Paintings_27_Neuvillette_3.webp",
    "Wriothesley": "Icon_Emoji_Paimon's_Paintings_27_Wriothesley_2.webp",
    "Furina": "Icon_Emoji_Paimon's_Paintings_26_Furina_1.webp",
    "Charlotte": "Icon_Emoji_Paimon's_Paintings_28_Charlotte_3.webp",
    "Navia": "Icon_Emoji_Paimon's_Paintings_29_Navia_3.webp",
    "Chevreuse": "Icon_Emoji_Paimon's_Paintings_29_Chevreuse_4.webp",
    "Xianyun": "Icon_Emoji_Paimon's_Paintings_30_Xianyun_1.webp",
    "Gaming": "Icon_Emoji_Paimon's_Paintings_30_Gaming_4.webp",
    "Chiori": "Icon_Emoji_Paimon's_Paintings_31_Chiori_1.webp",
    "Arlecchino": "Icon_Emoji_Paimon's_Paintings_32_Arlecchino_1.webp",
    "Sethos": "Icon_Emoji_Paimon's_Paintings_33_Sethos_1.webp",
    "Sigewinne": "Icon_Emoji_Paimon's_Paintings_33_Sigewinne_3.webp",
    "Clorinde": "Icon_Emoji_Paimon's_Paintings_28_Clorinde_1.webp",
    "Emilie": "",
    "Kachina": "Icon_Emoji_TEMP_Kachina_1.png",
    "Mualani": "Icon_Emoji_TEMP_Mualani_1.png",
    "Kinich": "Icon_EmojiTEMP__Kinich_1.png",
    "Xilonen": ""
}