const weapons =
    [
        "Akuoumaru",
        "Alley Hunter",
        "Amenoma Kageuchi",
        "Amos' Bow",
        "Apprentice's Notes",
        "Aqua Simulacra",
        "Aquila Favonia",
        "A Thousand Floating Dreams",
        "Ballad of the Fjords",
        "Beacon of the Reed Sea",
        "Beginner's Protector",
        "Blackcliff Agate",
        "Blackcliff Longsword",
        "Blackcliff Pole",
        "Blackcliff Slasher",
        "Blackcliff Warbow",
        "Black Tassel",
        "Bloodtainted Greatsword",
        "Calamity Queller",
        "Cinnabar Spindle",
        "Compound Bow",
        "Cool Steel",
        "Crescent Pike",
        "Dark Iron Sword",
        "Deathmatch",
        "Debate Club",
        "Dodoco Tales",
        "Dragon's Bane",
        "Dragonspine Spear",
        "Dull Blade",
        "Elegy for the End",
        "Emerald Orb",
        "End of the Line",
        "Engulfing Lightning",
        "Everlasting Moonglow",
        "Eye of Perception",
        "Fading Twilight",
        "Favonius Codex",
        "Favonius Greatsword",
        "Favonius Lance",
        "Favonius Sword",
        "Favonius Warbow",
        "Ferrous Shadow",
        "Festering Desire",
        "Fillet Blade",
        "Finale of the Deep",
        "Fleuve Cendre Ferryman",
        "Flowing Purity",
        "Forest Regalia",
        "Freedom-Sworn",
        "Frostbearer",
        "Fruit of Fulfillment",
        "Hakushin Ring",
        "Halberd",
        "Hamayumi",
        "Haran Geppaku Futsu",
        "Harbinger of Dawn",
        "Hunter's Bow",
        "Hunter's Path",
        "Ibis Piercer",
        "Iron Point",
        "Iron Sting",
        "Jadefall's Splendor",
        "Kagotsurube Isshin",
        "Kagura's Verity",
        "Katsuragikiri Nagamasa",
        "Key of Khaj-Nisut",
        "King's Squire",
        "Kitain Cross Spear",
        "Light of Foliar Incision",
        "Lion's Roar",
        "Lithic Blade",
        "Lithic Spear",
        "Lost Prayer to the Sacred Winds",
        "Luxurious Sea-Lord",
        "Magic Guide",
        "Mailed Flower",
        "Makhaira Aquamarine",
        "Mappa Mare",
        "Memory of Dust",
        "Messenger",
        "Missive Windspear",
        "Mistsplitter Reforged",
        "Mitternachts Waltz",
        "Moonpiercer",
        "Mouun's Moon",
        "Oathsworn Eye",
        "Old Merc's Pal",
        "Otherworldly Story",
        "Pocket Grimoire",
        "Polar Star",
        "Predator",
        "Primordial Jade Cutter",
        "Primordial Jade Winged-Spear",
        "Prized Isshin Blade",
        "Prized Isshin Blade",
        "Prized Isshin Blade",
        "Prototype Amber",
        "Prototype Archaic",
        "Prototype Crescent",
        "Prototype Rancour",
        "Prototype Starglitter",
        "Rainslasher",
        "Raven Bow",
        "Recurve Bow",
        "Redhorn Stonethresher",
        "Rightful Reward",
        "Royal Bow",
        "Royal Greatsword",
        "Royal Grimoire",
        "Royal Longsword",
        "Royal Spear",
        "Rust",
        "Sacrificial Bow",
        "Sacrificial Fragments",
        "Sacrificial Greatsword",
        "Sacrificial Jade",
        "Sacrificial Sword",
        "Sapwood Blade",
        "Scion of the Blazing Sun",
        "Seasoned Hunter's Bow",
        "Serpent Spine",
        "Sharpshooter's Oath",
        "Silver Sword",
        "Skyrider Greatsword",
        "Skyrider Sword",
        "Skyward Atlas",
        "Skyward Blade",
        "Skyward Harp",
        "Skyward Pride",
        "Skyward Spine",
        "Slingshot",
        "Snow-Tombed Starsilver",
        "Solar Pearl",
        "Song of Broken Pines",
        "Song of Stillness",
        "Staff of Homa",
        "Staff of the Scarlet Sands",
        "Summit Shaper",
        "Sword of Descension",
        "Talking Stick",
        "The Alley Flash",
        "The Bell",
        "The Black Sword",
        "The Catch",
        "The First Great Magic",
        "The Flute",
        "The Stringless",
        "The Unforged",
        "The Viridescent Hunt",
        "The Widsith",
        "Thrilling Tales of Dragon Slayers",
        "Thundering Pulse",
        "Tidal Shadow",
        "Toukabou Shigure",
        "Traveler's Handy Sword",
        "Tulaytullah's Remembrance",
        "Twin Nephrite",
        "Vortex Vanquisher",
        "Wandering Evenstar",
        "Waster Greatsword",
        "Wavebreaker's Fin",
        "Whiteblind",
        "White Iron Greatsword",
        "White Tassel",
        "Windblume Ode",
        "Wine and Song",
        "Wolf-Fang",
        "Wolf's Gravestone",
        "Xiphos' Moonlight"
    ]